"""Pydantic validation and serialization schemas package."""

from app.schemas.token import Token, TokenPayload
from app.schemas.user import (
    CustomerProfileBase,
    CustomerProfileCreate,
    CustomerProfileResponse,
    CustomerProfileUpdate,
    LoginRequest,
    ProviderProfileSummary,
    UserBase,
    UserCreate,
    UserPasswordUpdate,
    UserProfileUpdate,
    UserRegisterCustomer,
    UserRegisterRequest,
    UserResponse,
    UserUpdate,
)
from app.schemas.provider import (
    ProviderFilter,
    ProviderProfileBase,
    ProviderProfileCreate,
    ProviderProfileResponse,
    ProviderProfileUpdate,
    ProviderRegisterRequest,
    ProviderServiceBase,
    ProviderServiceCreate,
    ProviderServiceResponse,
    ProviderServiceUpdate,
)
from app.schemas.service import (
    ServiceCategoryBase,
    ServiceCategoryCreate,
    ServiceCategoryResponse,
    ServiceCategoryUpdate,
)
from app.schemas.request import (
    ALLOWED_STATUS_TRANSITIONS,
    ServiceRequestBase,
    ServiceRequestCreate,
    ServiceRequestResponse,
    ServiceRequestStatusUpdate,
    ServiceRequestUpdate,
    validate_status_transition,
)
from app.schemas.message import MessageBase, MessageCreate, MessageResponse
from app.schemas.review import (
    ReviewBase,
    ReviewCreate,
    ReviewResponse,
    VerificationRecordBase,
    VerificationRecordCreate,
    VerificationRecordResponse,
    VerificationRecordUpdate,
)

__all__ = [
    "Token",
    "TokenPayload",
    "CustomerProfileBase",
    "CustomerProfileCreate",
    "CustomerProfileResponse",
    "CustomerProfileUpdate",
    "LoginRequest",
    "ProviderProfileSummary",
    "UserBase",
    "UserCreate",
    "UserPasswordUpdate",
    "UserProfileUpdate",
    "UserRegisterCustomer",
    "UserRegisterRequest",
    "UserResponse",
    "UserUpdate",
    "ProviderFilter",
    "ProviderProfileBase",
    "ProviderProfileCreate",
    "ProviderProfileResponse",
    "ProviderProfileUpdate",
    "ProviderRegisterRequest",
    "ProviderServiceBase",
    "ProviderServiceCreate",
    "ProviderServiceResponse",
    "ProviderServiceUpdate",
    "ServiceCategoryBase",
    "ServiceCategoryCreate",
    "ServiceCategoryResponse",
    "ServiceCategoryUpdate",
    "ALLOWED_STATUS_TRANSITIONS",
    "ServiceRequestBase",
    "ServiceRequestCreate",
    "ServiceRequestResponse",
    "ServiceRequestStatusUpdate",
    "ServiceRequestUpdate",
    "validate_status_transition",
    "MessageBase",
    "MessageCreate",
    "MessageResponse",
    "ReviewBase",
    "ReviewCreate",
    "ReviewResponse",
    "VerificationRecordBase",
    "VerificationRecordCreate",
    "VerificationRecordResponse",
    "VerificationRecordUpdate",
]
